### ISSUE TITLE
image_widget_factory.rbでopenした画像ファイルがcloseされていない

### ISSUE THREAD

**Issue by Akkiesoft** [moguno/mikutter-uwm-hommage#3]
画像ファイルを選択すると、mikutterを終了するまでその画像ファイルが掴まれたままになるようです。掴まれっぱなしだと、アップロードした画像がmikutterを閉じないと削除できないみたいな感じになります。

おそらく、タイトルの通りimage_widget_factory.rbでopenした画像ファイルがcloseされていないのが原因かと思うのですが、Ruby力が低いのでプルリクできず。
ヽ('ω')ﾉ三ヽ('ω')ﾉもうしわけねぇもうしわけねぇ
[参考: http://qa.atmarkit.co.jp/q/58](http://qa.atmarkit.co.jp/q/58)

ご確認いただけますと幸いですん。

**Comment by moguno** [comment]
ありがとうございます。
ファイルの中身をキャッシュして即閉じるようにしました。

お時間あるときに確認をおねがいします。

**Comment by Akkiesoft** [comment]
確認できました！ヽ('ω')ﾉ三ヽ('ω')ﾉありがてえありがてえ
