### ISSUE TITLE
mikutter 3.6にこのプラグインを入れているとPostboxが増える

### ISSUE THREAD

**Issue by toshia** [moguno/mikutter-uwm-hommage#6]
他のプラグインに関わらず、このプラグインがあると、投稿後に有効なpostboxが一つ増えます。詳しく検証できてないのですが、取り急ぎ問題の共有をします。

![deepinscreenshot_select-area_20171222074827](https://user-images.githubusercontent.com/586906/34278167-9a28f6d4-e6ec-11e7-82e6-d2d862e6e7e2.png)

以下のチケット報告で判明しました。

https://dev.mikutter.hachune.net/issues/1123

投稿時に出るデバッグ出力は以下の通りです。

```
warning: /usr/lib/ruby/2.4.0/rubygems/deprecate.rb:62:in `block (2 levels) in deprecate': NOTE: Plugin::Twitter::World#post is deprecated; use spell (see: https://reference.mikutter.hachune.net/reference/2017/11/28/spell.html#compose-twitter) instead. It will be removed on or after 2018-11-01.
Plugin::Twitter::World#post called from /tmp/mikutter-confroots/develop/plugin/mikutter-uwm-hommage/postbox.rb:91.
```

**Comment by toshia** [comment]
もぐのさんなので雑に投げちゃいましたが、もし調査した結果mikutterが悪そうということになれば、当然mikutter側を修正するので、教えてください。

**Comment by tsutsui** [comment]
mikutter-uwm-hommage/postbox.rb が
https://dev.mikutter.hachune.net/projects/mikutter/repository/revisions/2fdb3315a1fc0804bc01bb41eaafe948faeedd25/entry/core/mui/gtk_postbox.rb#L145
の post_it をモンキーパッチ(?)していて、mikutter 本体のほうが更新されてしまったということだと思いますが、そもそも互換レイヤーが success が返ってきてないんですかね

**Comment by tsutsui** [comment]
mikutter 本体の gtk_postbox.rb に合わせて修正したら動いている（投稿後postboxがdestroyされる）っぽいです
https://gist.github.com/tsutsui/484a5a45d873ee7fa487752f06840999

**Comment by tsutsui** [comment]
インデントがずれてるという指摘があったのと、3.5.xでも場合分けすれば動くのかなあ、ということでテキトーに書いてみました https://gist.github.com/tsutsui/1011812b7082d8f07718af9b989595c7

**Comment by moguno** [comment]
つついさんのパッチをちょっとアレンジしつつ適用しました。0.4.6になります。
